# Generated by Django 4.0.4 on 2023-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_instantiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
